### PR TITLE
Listen for telegram:invoke event to allow using Telegram specific functionality

### PR DESCRIPTION
**Pull request by xPaw**
This is useful for doing stuff like image/audio uploads, and sending chat actions (e.g. recording audio).

### CODE REVIEW

**Comment by arcturial** [comment]
Instead of baking this logic into the adapter itself, wouldn't it be better to have the scripts execute the functionality directly. Since the scripts are already doing something "'Telegram specific" it would make sense if they contained the logic. I am assuming your script looks something like:

```
module.exports = (robot) ->
    robot.hear /some script text\b/i, (msg) ->
        robot.emit 'telegram:invoke', method, opts, callback
```

I am suggesting changing it to:

```
module.exports = (robot) ->
    robot.hear /some script text\b/i, (msg) ->
       robot.adapter.api.invoke method, opts, callback
```

That way you can do a `robot.adapter instanceof Telegram` if you want to create fallback logic in case the adapter in your Hubot changes.

**Comment by xPaw** [comment]
It's saner to emit an event though, as hubot documentation suggests.

**Comment by arcturial** [comment]
Can you point me to the documentation entry please?

**Comment by xPaw** [comment]
https://github.com/github/hubot/blob/master/docs/scripting.md#events

**Comment by arcturial** [comment]
Makes sense, I was thinking of having the logic being handled external from the adapter. However, in this case the event listener in the adapter already keeps it apart from the rest of the code. 

@lukefx what's your opinion on the subject?

**Pull request merged**
